ARG BASE_ID=latest
FROM ghcr.io/ppoi/devcontainer-images/base:${BASE_ID}

ARG NODE_VERSION=lts
ARG APT_PACKAGES=

USER vscode

RUN sudo /opt/setup-tools/install-n.sh ${NODE_VERSION} \
  && sudo /opt/setup-tools/install-apt-packages.sh libatomic1 ${APT_PACKAGES} \
  && curl -fsSL https://get.pnpm.io/install.sh | ENV="/home/vscode/.bashrc" SHELL="$(which bash)" bash -
