ARG BASE_ID=20250701
FROM ghcr.io/ppoi/devcontainer-images/base:${BASE_ID}

ARG NODE_VERSION=lts
ARG APT_PACKAGES=

RUN /opt/setup-tools/install-n.sh ${NODE_VERSION}
RUN /opt/setup-tools/install-apt-packages.sh ${APT_PACKAGES}
RUN curl -fsSL https://get.pnpm.io/install.sh | ENV="/home/vscode/.bashrc" SHELL="$(which bash)" sudo -u vscode bash -

USER vscode
