ARG BASE_ID=20240612-01
FROM ghcr.io/ppoi/devcontainer-images/base:${BASE_ID}

ARG JAVA_VERSION=21
ARG NODE_VERSION=lts
ARG MAVEN_VERSION=3.9.7
ARG APT_PACKAGES=

RUN /opt/setup-tools/install-n.sh ${NODE_VERSION}
RUN /opt/setup-tools/install-deb.sh https://packages.microsoft.com/config/debian/$(. /etc/os-release && echo "$VERSION_ID")/packages-microsoft-prod.deb
RUN /opt/setup-tools/install-apt-packages.sh msopenjdk-${JAVA_VERSION} ${APT_PACKAGES}
RUN /opt/setup-tools/install-maven.sh ${MAVEN_VERSION}

USER vscode
VOLUME /workspaces