ARG BASE_ID=latest
FROM ghcr.io/ppoi/devcontainer-images/base:${BASE_ID}

ARG JAVA_VERSION=21
ARG NODE_VERSION=lts
ARG MAVEN_VERSION=3.9.14
ARG APT_PACKAGES=

RUN /opt/setup-tools/install-n.sh ${NODE_VERSION} \
  && /opt/setup-tools/install-msopenjdk.sh ${JAVA_VERSION} doxygen doxygen-awesome-css ${APT_PACKAGES} \
  && /opt/setup-tools/install-maven.sh ${MAVEN_VERSION} \
  && RUN curl -fsSL https://get.pnpm.io/install.sh | ENV="/home/vscode/.bashrc" SHELL="$(which bash)" sudo -u vscode bash -

USER vscode
