ARG BASE_ID=20240924-01
FROM ghcr.io/ppoi/devcontainer-images/base:${BASE_ID}

ARG JAVA_VERSION=21
ARG NODE_VERSION=lts
ARG MAVEN_VERSION=3.9.9
ARG APT_PACKAGES=

RUN /opt/setup-tools/install-n.sh ${NODE_VERSION}
RUN /opt/setup-tools/install-msopenjdk.sh ${JAVA_VERSION} doxygen doxygen-awesome-css ${APT_PACKAGES}
RUN /opt/setup-tools/install-maven.sh ${MAVEN_VERSION}

USER vscode
VOLUME /workspaces