ARG BASE_ID=20240612-01
FROM ghcr.io/ppoi/devenv-base:20240512-01

ARG JAVA_VERSION=21
ARG MAVEN_VERSION=3.9.6
ARG APT_PACKAGES=

RUN /opt/setup-tools/install-deb.sh https://packages.microsoft.com/config/debian/$(. /etc/os-release && echo "$VERSION_ID")/packages-microsoft-prod.deb
RUN /opt/setup-tools/install-apt-packages.sh msopenjdk-${JAVA_VERSION} ${APT_PACKAGES}
RUN /opt/setup-tools/install-maven.sh ${MAVEN_VERSION}

USER vscode
VOLUME /workspaces