FROM docker.io/debian:bookworm-20250630-slim

ADD scripts /opt/setup-tools
RUN chmod -R 755 /opt/setup-tools

RUN /opt/setup-tools/install-apt-packages.sh sudo curl ca-certificates locales-all git zip unzip gpg openssl iproute2 iputils-ping net-tools procps socat

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor > /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
RUN /opt/setup-tools/install-apt-packages.sh docker-ce-cli
RUN groupadd --system docker

RUN /opt/setup-tools/install-awscli.sh

RUN useradd --uid 1000 --create-home --shell /bin/bash vscode && usermod -aG docker vscode && echo "vscode ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/vscode
RUN tee -a /home/vscode/.bashrc <<"EOF"
# bash theme - partly inspired by https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/robbyrussell.zsh-theme
__bash_prompt() {
    local userpart='`export XIT=$? \
        && [ ! -z "${GITHUB_USER}" ] && echo -n "\[\033[0;32m\]@${GITHUB_USER} " || echo -n "\[\033[0;32m\]\u " \
        && [ "$XIT" -ne "0" ] && echo -n "\[\033[1;31m\]➜" || echo -n "\[\033[0m\]➜"`'
    local gitbranch='`\
        if [ "$(git config --get devcontainers-theme.hide-status 2>/dev/null)" != 1 ] && [ "$(git config --get codespaces-theme.hide-status 2>/dev/null)" != 1 ]; then \
            export BRANCH=$(git --no-optional-locks symbolic-ref --short HEAD 2>/dev/null || git --no-optional-locks rev-parse --short HEAD 2>/dev/null); \
            if [ "${BRANCH}" != "" ]; then \
                echo -n "\[\033[0;36m\](\[\033[1;31m\]${BRANCH}" \
                && if [ "$(git config --get devcontainers-theme.show-dirty 2>/dev/null)" = 1 ] && \
                    git --no-optional-locks ls-files --error-unmatch -m --directory --no-empty-directory -o --exclude-standard ":/*" > /dev/null 2>&1; then \
                        echo -n " \[\033[1;33m\]✗"; \
                fi \
                && echo -n "\[\033[0;36m\]) "; \
            fi; \
        fi`'
    local lightblue='\[\033[1;34m\]'
    local removecolor='\[\033[0m\]'
    PS1="${userpart} ${lightblue}\w ${gitbranch}${removecolor}\$ "
    unset -f __bash_prompt
}
__bash_prompt
export PROMPT_DIRTRIM=4

# docker socket proxy
__docker_proxy() {
    if [ -S /var/run/docker.sock ] && [ "$(ls -l /var/run/docker.sock | awk '{print $4}')" != "docker" ]; then
        PROXY_SOCK="/tmp/docker-proxy.sock"
        PROXY_PID="/tmp/docker-proxy.pid"
        if [ ! -f "${PROXY_PID}" ] || ! ps -p $(cat ${PROXY_PID}) > /dev/null; then
            sudo rm -rf "${PROXY_PID}" "${PROXY_SOCK}"
            (sudo socat UNIX-LISTEN:${PROXY_SOCK},fork,mode=660,user=vscode,backlog=128 UNIX-CONNECT:/var/run/docker.sock 2>&1 >/dev/null & echo "$!" | sudo tee ${PROXY_PID} > /dev/null)
        fi
        DOCKER_HOST="unix://${PROXY_SOCK}"
        export DOCKER_HOST
    fi
    unset -f __docker_proxy
}
__docker_proxy

# XDG Base Directory Specification
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_STATE_HOME="${HOME}/.local/state"
EOF