ARG BASE_ID=20240901-01
FROM ghcr.io/ppoi/devcontainer-images/base:${BASE_ID}

ARG JAVA_VERSION=21
ARG MAVEN_VERSION=3.9.9
ARG APT_PACKAGES=

RUN /opt/setup-tools/install-msopenjdk.sh ${JAVA_VERSION} doxygen doxygen-awesome-css ${APT_PACKAGES}
RUN /opt/setup-tools/install-maven.sh ${MAVEN_VERSION}

USER vscode
ENV MAVEN_ARGS="-Dmaven.repo.local=/workspaces/.mvn"
VOLUME /workspaces