name: "release images"

on:
  push:
    tags:
      - "*"

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Collect metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: type=ref,event=tag
      - name: Build base image
        id: base
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Containerfile
          tags: ghcr.io/${{github.actor}}/devcontainer-images/base:${{steps.meta.outputs.version}},ghcr.io/${{github.actor}}/devcontainer-images/base:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      - name: Build Type-ALPHA image
        id: type-alpha
        uses: docker/build-push-action@v5
        with:
          context: ./src/type-alpha
          file: ./src/type-alpha/Containerfile
          build-args: |
            BASE_ID=${{steps.meta.outputs.version}}
          tags: ghcr.io/${{github.actor}}/devcontainer-images/type-alpha:${{steps.meta.outputs.version}},ghcr.io/${{github.actor}}/devcontainer-images/type-alpha:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      - name: Build Type-BRAVO image
        id: type-bravo
        uses: docker/build-push-action@v5
        with:
          context: ./src/type-bravo
          file: ./src/type-bravo/Containerfile
          build-args: |
            BASE_ID=${{steps.meta.outputs.version}}
          tags: ghcr.io/${{github.actor}}/devcontainer-images/type-bravo:${{steps.meta.outputs.version}},ghcr.io/${{github.actor}}/devcontainer-images/type-bravo:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      - name: Build Type-CHARLIE image
        id: type-charlie
        uses: docker/build-push-action@v5
        with:
          context: ./src/type-charlie
          file: ./src/type-charlie/Containerfile
          build-args: |
            BASE_ID=${{steps.meta.outputs.version}}
          tags: ghcr.io/${{github.actor}}/devcontainer-images/type-charlie:${{steps.meta.outputs.version}},ghcr.io/${{github.actor}}/devcontainer-images/type-charilie:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true
